# 描述/签名
name: 刻莱诺图书馆
description: Kelaino Library

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: https://thelemia.github.io
# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /book

# [可选]博客logo图片URL，建议尺寸不超过300px × 300px
# avatar: https://ovo.wxw.media/media_attachments/files/109/310/828/701/996/843/original/62f95928bd0b6a3c.png
# [可选]favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://ovo.wxw.media/media_attachments/files/109/310/828/701/996/843/original/62f95928bd0b6a3c.png

# 菜单中的按钮
# navigation:
#   - name: 首页
#     url: https://thelemia.github.io/home
#   - name: 关于
#     url: https://thelemia.github.io/about
#   - name: 归档
#     url: https://thelemia.github.io/book
#   - name: 标签
#     url: https://thelemia.github.io/tags
    
    default:
          body:
            theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: true # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
          html_lang: zh # <https://www.w3school.com.cn/tags/html_ref_language_codes.asp>
          sidebar: # 此配置项下是一些关于侧边栏的配置
            disable: false # 是否不显示sidebar
            avatar: # 侧边栏显示的头像
              enable: true
              img: https://ovo.wxw.moe/media_attachments/files/109/310/632/338/710/994/original/6b15dd6722fed88c.jpg # 头像地址
            nav: # 导航部分的内容，你也可以自己增加文字、图标（来自fontawesome）和对应的链接
              - title: '<i class="fa-solid fa-home fa-fw"></i> 首页'
                href: /
              - title: '<i class="fa-solid fa-comment fa-fw"></i> 留言'
                href: /comments/
              - title: '<i class="fa-solid fa-archive fa-fw"></i> 归档'
                href: /archive/
              - title: '<i class="fa-solid fa-tags fa-fw"></i> 标签'
                href: /tags/
              - title: '<i class="fa-solid fa-coffee fa-fw"></i> 打赏'
                href: /merger/
            simple_jekyll_search: # 侧边栏的全站搜索
              enable: true
              full_text_search: false # 可能导致缓慢的搜索和加载
              append: | # 如果看不懂就不改
                <style>
                  #sidebar-search-input {
                    background: none;
                    border: none;
                    color: White;
                    width: 100%;
                  }
                  #sidebar-search-results-container {
                    overflow: hidden hidden;
                    max-height: 66.6vh;
                  }
                  #sidebar-search-results-container:hover {
                    overflow: auto auto;
                  }
                </style>
                <input
                  id="sidebar-search-input"
                  placeholder="搜索博文"
                />
                <ol
                  id="sidebar-search-results-container"
                ></ol>
                <script
                  src='https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.9.1'
                  async='async'
                  onload='
                    SimpleJekyllSearch({
                      json: "/assets/simple-jekyll-search/search.json",
                      searchInput: document.getElementById("sidebar-search-input"),
                      resultsContainer: document.getElementById("sidebar-search-results-container"),
                      searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                      limit: 99,
                      fuzzy: true
                    })'
                ></script>
            jekyll-toc: # 侧边栏的目录插件，https://github.com/allejo/jekyll-toc
              enable: true
              prepend: | # 目录过长时自动折叠
                <style>
                  #toc {
                    overflow: hidden hidden;
                    max-height: 66.6vh;
                  }
                  #toc:hover{
                    overflow: auto auto;
                  }
                </style>
            append_to_sidebar:
              #- <script defer="defer" src="https://cdn.jsdelivr.net/gh/poole/lanyon@v1.1.0/public/js/script.min.js"></script> # 点击空白处而非按钮从而关闭侧边栏的插件，可选
              - | # 侧边栏使用主题色
                <style>
                  #sidebar-checkbox:checked ~ .sidebar-toggle,
                  .sidebar,
                  .sidebar-toggle:active {
                    background-color: var(--theme-base-color);
                  }
                </style>
              - | # 修复点击侧边栏按钮回到顶部的问题
                <style>
                  .sidebar-checkbox {
                    display: none;
                  }
                  .sidebar-toggle {
                    position: fixed;
                    background: none;
                  }
                </style>
              - | # 修复侧边栏特定情况下抖动的问题，感谢 [@AmachiInori](https://github.com/wu-kan/wu-kan.github.io/issues/11)
                <style>
                  .sidebar {
                    overflow: hidden;
                    min-height: 101%;
                  }
                  .sidebar:hover{
                    overflow-y: scroll; 
                  }
                </style>
              - | # 侧边栏头像效果
                <style>
                  .effect {
                    margin: 1rem;
                    perspective: 900px;
                  }
                  .effect-info {
                    text-align: center;
                    position: absolute;
                    top: 0;
                    width: 100%;
                    transform-style: preserve-3d;
                  }
                  .effect-img {
                    z-index: 11;
                    width: 100%;
                    height: 100%;
                    position: relative;
                    transition: all 0.5s ease-in-out;
                  }
                  .effect-img:before {
                    position: absolute;
                    display: block;
                  }
                  .effect-right_to_left .effect-img {
                    transform-origin: 0% 50%;
                  }
                  .effect-right_to_left:hover .effect-img {
                    transform: rotate3d(0, 1, 0, -180deg);
                  }
                </style>
              - | # 运行时间，可将倒数第三行的时间改成你自己的建站时间，格式仿照上面的；不需要的话可以把这一项都删掉
                <div>
                  <i class="fa-solid fa-cog fa-spin fa-fw"></i>
                  <span id="run_time_day">
                    <i class="fa-solid fa-spinner fa-pulse"></i>
                  </span>天
                  <span id="run_time_hour">
                    <i class="fa-solid fa-spinner fa-pulse"></i>
                  </span>时
                  <span id="run_time_minute">
                    <i class="fa-solid fa-spinner fa-pulse"></i>
                  </span>分
                  <span id="run_time_second">
                    <i class="fa-solid fa-spinner fa-pulse"></i>
                  </span>秒
                  <script>
                    setInterval(function (d,h,m,s,b) {
                      function setzero(i) {
                        return i < 10 ? "0" + i : i;
                      }
                      let BirthDay = new Date(b);
                      let today = new Date();
                      let timeold = (today.getTime() - BirthDay.getTime());
                      let sectimeold = timeold / 1000;
                      let secondsold = Math.floor(sectimeold);
                      let msPerDay = 24 * 60 * 60 * 1000;
                      let e_daysold = timeold / msPerDay;
                      let daysold = Math.floor(e_daysold);
                      let e_hrsold = (e_daysold - daysold) * 24;
                      let hrsold = Math.floor(e_hrsold);
                      let e_minsold = (e_hrsold - hrsold) * 60;
                      let minsold = Math.floor((e_hrsold - hrsold) * 60);
                      let seconds = Math.floor((e_minsold - minsold) * 60);
                      d.textContent = daysold;
                      h.textContent = setzero(hrsold);
                      m.textContent = setzero(minsold);
                      s.textContent = setzero(seconds);
                    },
                    1000,
                    document.getElementById("run_time_day"),
                    document.getElementById("run_time_hour"),
                    document.getElementById("run_time_minute"),
                    document.getElementById("run_time_second"),
                    "10/04/2017 11:03:56")// 这是我第一篇CSDN博客的时间
                  </script>
                </div>
              - | # 不蒜子页面统计，看不懂可不改
                <div>
                  <div>
                    <i class="fa-solid fa-eye fa-fw"></i>
                    <span id="busuanzi_value_page_pv">
                      <i class="fa-solid fa-spinner fa-pulse"></i>
                    </span>次
                  </div>
                  <div>
                    <i class="fa-solid fa-paw fa-fw"></i>
                    <span id="busuanzi_value_site_pv">
                      <i class="fa-solid fa-spinner fa-pulse"></i>
                    </span>枚
                  </div>
                  <div>
                    <i class="fa-solid fa-user-friends fa-fw"></i>
                    <span id="busuanzi_value_site_uv">
                      <i class="fa-solid fa-spinner fa-pulse"></i>
                    </span>人
                  </div>
                  <script
                    src='https://cdn.jsdelivr.net/npm/busuanzi@2.3/bsz.pure.mini.js'
                    async='async'
                  ></script>
                </div>

# 每页的文章数
paginate: 10

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: https://weibo.com/5018395824/profile?rightmod=1&wvr=6&mod=personinfo  #微博个性域名
  twitter: # https://www.twitter.com/<your_twitter_username> 
  email: witchstaynight@gmail.com #youremailaddress@mail.com

# 站点页脚的文字
footer-text: Copyright (c) 2022 刻莱诺图书馆

# 评论，注意，请不要同时添加多种不同的评论区
# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: thelemia #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
# gitalk:
#   clientID: 
#   clientSecret: 
#   repo: 
#   owner: 
#   proxy:

# 输入Google Analytics web tracking code
# google_analytics:
# utteranc:
#   repo: # Your github repo path, also see: https://utteranc.es

# !! 以下所有设置都不需要更改 !!

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

